### ISSUE TITLE
Invoke wrapper or gw

### ISSUE THREAD

**Issue by lwis** [florianb/atom-gradle-ci#10]
Would it be possible to define the executable, or alternatively attempt to use [gdub](https://github.com/dougborg/gdub) if it's on the path? 

Excellent work bumping for 1.0 btw!

**Comment by florianb** [comment]
Hi @lwis - thanks for your feedback. I would be happy to integrate alternative calls. Would you say this should be defined on a per-project basis or as a config-attribute?

**Comment by lwis** [comment]
Hi Florian,

If I have gdub installed, I use that for all my projects, same goes for
wrapper. I would suggest having a config that checks for gdub first, then
wrapper, then gradle as a last resort.

**Comment by florianb** [comment]
Thank you - i'll add a config-option, to enable alternative calls. I also thought about introducing config-files on a per project base. Probably something for a later release.

**Comment by florianb** [comment]
I guess i have completely understood what i need to do. The problem is, while i can systemwide replace a call for `gradle` instantly by a call of `gw`, gradle needs to be wrapped on a per project base to make `gradlew` available. Currently the package firstly approves the availability of gradle **before** enabling the build-functionality. If enabling the wrapper i'd have to check for the wrapper everytime the project-paths change. This will need a rewrite and i can imagine to implement it in a future release. Now i will add the option to try to call `gw` first. Thanks for your input so far! :beer:

**Comment by florianb** [comment]
added a preference to run `gw` by default over `gradle`.
